### ISSUE TITLE
ダウ理論

### ISSUE THREAD

**Issue by kaito1020** [Sakuraba119/SakurabaToDo#14]
利確参照

https://aspergerz.biz/dm

**Comment by kaito1020** [comment]
https://fxautotrading.jp/11631/

**Comment by Sarami0202** [comment]
@kaito1020 
デバッグに時間がかかって遅れました。
確認お願いします。

[(KEA)ZigZag＿DawT.zip](https://github.com/Sakuraba119/ToDo/files/8914061/KEA.ZigZag.DawT.zip)

**Comment by kaito1020** [comment]
@Sarami0202 結果的に使えそうな条件だった？

**Comment by Sarami0202** [comment]
利確はトレールが上手く機能してるみたいで良かったのですが、トレンドに乗れない時の損切りが多い印象でした。
