### ISSUE TITLE
byond

### ISSUE THREAD

**Issue by Sakuraba119** [Sakuraba119/SakurabaToDo#21]
vyondで使えるフォント収集
https://animedemo.com/userpages/fontosusume/
白抜き文字
https://animedemo.com/userpages/font202004/
3画面カラム
https://youtu.be/sCHMD1kiyoo
無料フォント？
https://youtu.be/gHO1zIOlsIw
強調
https://youtu.be/qMYOFSzlja4
文字読み
https://youtu.be/qMYOFSzlja4
ホワイトボードアニメーション
https://youtu.be/IhlW_-woJXo
vyond4k
https://youtu.be/MY7SOtZAk2U

**Comment by Sakuraba119** [comment]
素材
https://youtu.be/Jf_I53LDWjQ

**Comment by kaito1020** [comment]
[フォント.zip](https://github.com/Sakuraba119/SakurabaToDo/files/8928551/default.zip)

動画のテロップで使っているのはラノベポップv1

**Comment by kaito1020** [comment]
冷蔵庫搬入

リベラルアーツのようなものはビヨンドでのほうがいいのかプレミヤのほうがいいのか

**Comment by Sakuraba119** [comment]
素材単語
shape ←吹き出し　図形
triangle ←画面を分割　
line
cicre
mask
bubble
effect

**Comment by Sakuraba119** [comment]
フォント変更は有償化のみ
